/* ========================================
 * 错题练习数据库 - 举一反三练习题
 * 覆盖：数据结构、算法、操作系统、计算机网络、数据库、软件工程
 * ======================================== */

const PRACTICE_QUESTIONS = [
    // ========== 数据结构 ==========
    { id: 'q01', category: '数据结构', topic: '数组', difficulty: 1, type: 'choice',
      question: '在一个长度为 n 的数组中查找指定元素，线性查找的时间复杂度是？',
      options: ['O(1)', 'O(n)', 'O(log n)', 'O(n²)'], answer: 1,
      explanation: '线性查找需要逐个比较，最坏情况比较 n 次，时间复杂度 O(n)。二分查找才是 O(log n)。',
      related: ['q02', 'q03', 'q15'] },

    { id: 'q02', category: '数据结构', topic: '数组', difficulty: 2, type: 'choice',
      question: '动态数组（如 C++ vector）扩容时通常将容量翻倍，扩容的均摊时间复杂度是？',
      options: ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'], answer: 0,
      explanation: '虽然单次扩容 O(n)，但 n 次 push_back 只会触发约 log n 次扩容，总扩容成本 O(n)，均摊到每次 O(1)。',
      related: ['q01', 'q03'] },

    { id: 'q03', category: '数据结构', topic: '链表', difficulty: 1, type: 'choice',
      question: '以下关于单链表的说法，正确的是？',
      options: ['支持随机访问，时间复杂度 O(1)', '插入和删除操作的时间复杂度为 O(1)（已知节点位置）',
                '所占空间比数组小', '更适合频繁随机访问的场景'], answer: 1,
      explanation: '链表不支持随机访问（A错）；在已知节点位置时插入删除O(1)（B对）；链表有额外指针开销（C错）；链表适合频繁插入删除（D错）。',
      related: ['q04', 'q05', 'q01'] },

    { id: 'q04', category: '数据结构', topic: '链表', difficulty: 2, type: 'choice',
      question: '判断链表是否有环，最优的时间复杂度是？',
      options: ['O(n) 快慢指针', 'O(n²) 暴力', 'O(n log n)', 'O(1)'], answer: 0,
      explanation: '快慢指针法（Floyd判圈法）：快指针每次走2步，慢指针每次走1步，若有环则一定会相遇，时间O(n)，空间O(1)。',
      related: ['q03', 'q05', 'q06'] },

    { id: 'q05', category: '数据结构', topic: '栈', difficulty: 1, type: 'choice',
      question: '栈的特点是后进先出(LIFO)，以下哪个场景不适合用栈？',
      options: ['函数调用管理', '浏览器前进后退', '表达式求值（括号匹配）', '需要随机访问中间元素的场景'], answer: 3,
      explanation: '栈只允许在栈顶操作，无法随机访问中间元素。函数调用、浏览器后退、括号匹配都是栈的典型应用。',
      related: ['q06', 'q07', 'q03'] },

    { id: 'q06', category: '数据结构', topic: '队列', difficulty: 1, type: 'choice',
      question: '队列的特点是先进先出(FIFO)，广度优先搜索(BFS)使用队列的原因是？',
      options: ['队列保证按层级顺序访问节点', '队列访问速度最快', '队列可以随机访问', '队列占用空间最小'], answer: 0,
      explanation: 'BFS需要按距起点的距离逐层访问，队列的FIFO特性恰好保证先访问的节点其邻居也先被处理，实现层序遍历。',
      related: ['q05', 'q11', 'q15'] },

    { id: 'q07', category: '数据结构', topic: '哈希表', difficulty: 2, type: 'choice',
      question: '哈希表解决冲突的拉链法中，最坏情况下查找时间复杂度为？',
      options: ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'], answer: 2,
      explanation: '最坏情况所有键哈希到同一个桶，拉链法退化为链表，查找O(n)。平均情况下是O(1)。',
      related: ['q02', 'q08'] },

    { id: 'q08', category: '数据结构', topic: '二叉树', difficulty: 2, type: 'choice',
      question: '二叉树的中序遍历顺序是？',
      options: ['根→左→右', '左→根→右', '左→右→根', '根→右→左'], answer: 1,
      explanation: '中序遍历：左子树→根节点→右子树。对于二叉搜索树，中序遍历得到有序序列。前序是根左右，后序是左右根。',
      related: ['q09', 'q10', 'q11'] },

    { id: 'q09', category: '数据结构', topic: 'BST', difficulty: 2, type: 'choice',
      question: '二叉搜索树(BST)在最坏情况下退化为链表，查找复杂度变为？',
      options: ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'], answer: 2,
      explanation: '当按有序序列插入时（如1,2,3,4,5），BST退化为单链表，查找O(n)。平衡树（AVL/红黑树）可保证O(log n)。',
      related: ['q08', 'q10', 'q13'] },

    { id: 'q10', category: '数据结构', topic: 'AVL树', difficulty: 3, type: 'choice',
      question: 'AVL树在插入新节点后，如果平衡因子变为2，需要哪种旋转来恢复平衡？',
      options: ['LL型右旋', 'RR型左旋', 'LR型先左旋再右旋', 'RL型先右旋再左旋'],
      answer: 0,
      explanation: '平衡因子为2说明左子树比右子树高2。若新节点在左子树的左子树(LL)，需右旋；在左子树的右子树(LR)，需先左旋再右旋。',
      related: ['q09', 'q11', 'q08'] },

    { id: 'q11', category: '数据结构', topic: '堆', difficulty: 2, type: 'choice',
      question: '对于大顶堆，以下哪个说法正确？',
      options: ['左子节点一定大于右子节点', '父节点值大于等于所有子节点值',
                '堆是有序的数组', '堆中任意路径都是递增的'], answer: 1,
      explanation: '大顶堆只保证父节点>=子节点，不保证左右子节点的相对大小。堆不是完全有序的，只是根节点最大。',
      related: ['q12', 'q10', 'q06'] },

    { id: 'q12', category: '数据结构', topic: '图', difficulty: 2, type: 'choice',
      question: '对于有 V 个顶点、E 条边的稀疏图，使用哪种存储方式更节省空间？',
      options: ['邻接矩阵 O(V²)', '邻接表 O(V+E)', '边集数组 O(E)', '邻接矩阵更优'],
      answer: 1,
      explanation: '稀疏图 E<<V²，邻接表O(V+E)远小于邻接矩阵O(V²)。稠密图则邻接矩阵更优。',
      related: ['q11', 'q15', 'q16'] },

    // ========== 算法 ==========
    { id: 'q13', category: '算法', topic: '快速排序', difficulty: 2, type: 'choice',
      question: '快速排序在最坏情况下的时间复杂度是？',
      options: ['O(n log n)', 'O(n²)', 'O(n)', 'O(log n)'], answer: 1,
      explanation: '最坏情况：每次选到最值作为基准，分区极度不平衡（如已排序数组选第一个元素），退化为O(n²)。随机化pivot可避免。',
      related: ['q14', 'q16', 'q09'] },

    { id: 'q14', category: '算法', topic: '归并排序', difficulty: 2, type: 'choice',
      question: '归并排序的时间复杂度和空间复杂度分别是？',
      options: ['O(n log n) 时间, O(1) 空间', 'O(n log n) 时间, O(n) 空间',
                'O(n²) 时间, O(1) 空间', 'O(n log n) 时间, O(log n) 空间'],
      answer: 1,
      explanation: '归并排序始终O(n log n)时间，但合并两个有序数组需要O(n)额外空间。它是稳定排序，适合外部排序和链表排序。',
      related: ['q13', 'q16', 'q15'] },

    { id: 'q15', category: '算法', topic: '二分查找', difficulty: 2, type: 'choice',
      question: '二分查找的前提条件是？',
      options: ['数组必须是有序的', '数组必须是链表', '数组必须是完全二叉树', '数组大小必须是2的幂'],
      answer: 0,
      explanation: '二分查找依赖有序性来每轮排除一半的元素。无序数组需先排序O(n log n)或使用线性查找O(n)。',
      related: ['q01', 'q14', 'q16'] },

    { id: 'q16', category: '算法', topic: 'DFS', difficulty: 2, type: 'choice',
      question: '深度优先搜索(DFS)通常使用什么数据结构实现？',
      options: ['队列', '栈或递归', '堆', '哈希表'], answer: 1,
      explanation: 'DFS可以用递归（隐式使用系统调用栈）或显式栈实现。BFS用队列。DFS适合找所有解、连通性判断、拓扑排序。',
      related: ['q17', 'q06', 'q12'] },

    { id: 'q17', category: '算法', topic: '动态规划', difficulty: 3, type: 'choice',
      question: '动态规划的核心思想是？',
      options: ['贪心选择，每步取局部最优', '将问题分解为子问题，保存子问题解避免重复计算',
                '回溯所有可能', '分治后合并结果但不记录中间结果'],
      answer: 1,
      explanation: 'DP利用最优子结构和重叠子问题，通过记忆化或表格法保存子问题解。与分治的区别：分治的子问题独立不重叠，DP的子问题有重叠。',
      related: ['q18', 'q19', 'q16'] },

    { id: 'q18', category: '算法', topic: '贪心', difficulty: 2, type: 'choice',
      question: '以下哪个问题不能用贪心算法得到最优解？',
      options: ['Huffman编码', 'Dijkstra最短路径', '0-1背包问题', '最小生成树(Kruskal)'],
      answer: 2,
      explanation: '0-1背包问题（每件物品取或不取）不能贪心，因为按单位价值排序后选局部最优不一定全局最优，需用DP解决。分数背包可以贪心。',
      related: ['q17', 'q19', 'q20'] },

    { id: 'q19', category: '算法', topic: '回溯', difficulty: 3, type: 'choice',
      question: '回溯算法的时间复杂度通常为？',
      options: ['O(n)', 'O(n log n)', 'O(2^n) 或 O(n!)', 'O(n²)'],
      answer: 2,
      explanation: '回溯枚举所有可能，子集问题O(2^n)，排列问题O(n!)。通过剪枝可大幅减少实际运行时间，但最坏复杂度不变。',
      related: ['q17', 'q18', 'q20'] },

    { id: 'q20', category: '算法', topic: '滑动窗口', difficulty: 2, type: 'choice',
      question: '滑动窗口算法的时间复杂度通常是？',
      options: ['O(n²)', 'O(n)', 'O(n log n)', 'O(2^n)'],
      answer: 1,
      explanation: '滑动窗口中left和right指针各最多遍历一次，虽然嵌套while但总操作O(n)。适合解决连续子数组/子串问题。',
      related: ['q17', 'q19', 'q15'] },

    // ========== 操作系统 ==========
    { id: 'q21', category: '操作系统', topic: '进程与线程', difficulty: 1, type: 'choice',
      question: '以下关于进程和线程的说法，正确的是？',
      options: ['线程是资源分配的基本单位', '进程是CPU调度的基本单位',
                '线程共享进程的地址空间', '进程间切换比线程间切换快'],
      answer: 2,
      explanation: '进程是资源分配单位（A错），线程是CPU调度单位（B错），线程共享进程的地址空间（C对），线程切换不涉及地址空间切换所以更快（D错）。',
      related: ['q22', 'q23', 'q24'] },

    { id: 'q22', category: '操作系统', topic: '死锁', difficulty: 2, type: 'choice',
      question: '产生死锁的四个必要条件不包括？',
      options: ['互斥条件', '占有并等待', '不可抢占', '时间片轮转'],
      answer: 3,
      explanation: '死锁四条件：互斥、占有并等待、不可抢占、循环等待。时间片轮转是调度策略，与死锁无关。',
      related: ['q21', 'q23', 'q24'] },

    { id: 'q23', category: '操作系统', topic: '页面置换', difficulty: 2, type: 'choice',
      question: 'LRU页面置换算法淘汰的是？',
      options: ['最先进入内存的页面', '最近最长时间未被访问的页面',
                '访问频率最低的页面', '随机选择一个页面'],
      answer: 1,
      explanation: 'LRU(Least Recently Used)淘汰最近最久未使用的页面。FIFO淘汰最先进入的。LFU淘汰最不经常使用的。Optimal淘汰未来最久不被使用的。',
      related: ['q24', 'q21', 'q22'] },

    { id: 'q24', category: '操作系统', topic: 'I/O多路复用', difficulty: 3, type: 'choice',
      question: '关于 select、poll、epoll 的说法，正确的是？',
      options: ['select 没有文件描述符数量限制', 'poll 使用位图传递文件描述符',
                'epoll 使用回调机制，时间复杂度为 O(1)', 'epoll 不支持水平触发(LT)模式'],
      answer: 2,
      explanation: 'select有1024个FD限制（A错），poll用结构体数组（B错），epoll用红黑树+就绪链表+回调机制O(1)获取就绪事件（C对），epoll支持ET和LT两种模式（D错）。',
      related: ['q21', 'q23', 'q22'] },

    // ========== 计算机网络 ==========
    { id: 'q25', category: '计算机网络', topic: 'TCP握手', difficulty: 2, type: 'choice',
      question: 'TCP三次握手中，第二次握手报文的标志位是？',
      options: ['SYN', 'ACK', 'SYN + ACK', 'FIN + ACK'],
      answer: 2,
      explanation: '第二次握手：服务端回复 SYN=1, ACK=1，seq=y, ack=x+1，表示同意连接并确认收到客户端的SYN。',
      related: ['q26', 'q27', 'q28'] },

    { id: 'q26', category: '计算机网络', topic: 'TCP挥手', difficulty: 2, type: 'choice',
      question: 'TCP四次挥手中，主动关闭方在TIME_WAIT状态需要等待多长时间？',
      options: ['1个MSL', '2个MSL', '3个MSL', '4个MSL'],
      answer: 1,
      explanation: 'TIME_WAIT等待2MSL(最大报文段寿命)：1)确保最后一个ACK到达对端(若丢失可重传)；2)让旧连接的报文在网络中消失。',
      related: ['q25', 'q27', 'q28'] },

    { id: 'q27', category: '计算机网络', topic: 'TCP与UDP', difficulty: 1, type: 'choice',
      question: '以下哪个应用层协议使用的是 UDP？',
      options: ['HTTP', 'SSH', 'DNS', 'FTP'],
      answer: 2,
      explanation: 'DNS使用UDP端口53（查询量小、要求快速响应）。HTTP/SSH/FTP都基于TCP需要可靠传输。DNS在区域传送时也会用TCP。',
      related: ['q25', 'q26', 'q28'] },

    { id: 'q28', category: '计算机网络', topic: 'HTTP', difficulty: 1, type: 'choice',
      question: 'HTTP状态码 404 表示？',
      options: ['服务器内部错误', '请求的资源未找到', '请求被拒绝', '永久重定向'],
      answer: 1,
      explanation: '404 Not Found 表示服务器找不到请求的资源。500是服务器内部错误，403是禁止访问，301是永久重定向。',
      related: ['q27', 'q29', 'q30'] },

    { id: 'q29', category: '计算机网络', topic: 'HTTPS', difficulty: 2, type: 'choice',
      question: 'HTTPS在传输数据时使用的加密方式是？',
      options: ['仅使用非对称加密', '仅使用对称加密', '非对称加密交换密钥，对称加密传输数据', '不加密'],
      answer: 2,
      explanation: 'HTTPS先用非对称加密(RSA/ECDHE)安全交换会话密钥，之后通信用对称加密(AES)加密数据。这样兼顾安全性和性能。',
      related: ['q28', 'q30', 'q25'] },

    { id: 'q30', category: '计算机网络', topic: 'IP地址', difficulty: 2, type: 'choice',
      question: '以下哪个是私有IP地址？',
      options: ['8.8.8.8', '192.168.1.1', '114.114.114.114', '1.1.1.1'],
      answer: 1,
      explanation: '私有IP范围：10.0.0.0/8、172.16.0.0/12、192.168.0.0/16。192.168.1.1属于C类私有地址。其余都是公网IP。',
      related: ['q28', 'q29', 'q27'] },

    // ========== 数据库 ==========
    { id: 'q31', category: '数据库', topic: 'SQL基础', difficulty: 1, type: 'choice',
      question: 'SQL中用于去重的关键字是？',
      options: ['UNIQUE', 'DISTINCT', 'GROUP BY', 'ORDER BY'],
      answer: 1,
      explanation: 'DISTINCT用于SELECT查询去除重复行。UNIQUE是约束关键字。GROUP BY用于分组聚合。ORDER BY用于排序。',
      related: ['q32', 'q33', 'q34'] },

    { id: 'q32', category: '数据库', topic: '索引', difficulty: 2, type: 'choice',
      question: 'MySQL InnoDB的聚簇索引是指？',
      options: ['数据按主键顺序存储，索引和数据在一起', '索引和数据分开存储', '所有索引都是聚簇索引', '只有非主键索引才是聚簇索引'],
      answer: 0,
      explanation: 'InnoDB的聚簇索引：叶子节点存储完整数据行，按主键排序。非聚簇索引(二级索引)存主键值，需要回表查询。覆盖索引可避免回表。',
      related: ['q31', 'q33', 'q34'] },

    { id: 'q33', category: '数据库', topic: '事务ACID', difficulty: 2, type: 'choice',
      question: '事务的隔离性(Isolation)是为了解决什么问题？',
      options: ['数据丢失', '并发事务之间的相互干扰', '数据完整性', '事务原子性'],
      answer: 1,
      explanation: '隔离性保证并发事务执行时互不干扰。隔离级别：读未提交<读已提交<可重复读<串行化。隔离性通过锁和MVCC实现。',
      related: ['q32', 'q34', 'q35'] },

    { id: 'q34', category: '数据库', topic: 'MVCC', difficulty: 3, type: 'choice',
      question: '在MySQL可重复读(REPEATABLE READ)隔离级别下，MVCC的ReadView是在何时创建的？',
      options: ['事务开始时', '第一次执行SELECT时', '每次执行SELECT时', '事务提交时'],
      answer: 1,
      explanation: '可重复读：第一次SELECT创建ReadView并复用，后续SELECT都用同一个ReadView，保证可重复读。读已提交：每次SELECT都创建新ReadView。',
      related: ['q33', 'q32', 'q35'] },

    { id: 'q35', category: '数据库', topic: '数据库锁', difficulty: 2, type: 'choice',
      question: 'MySQL InnoDB在可重复读级别下，使用什么锁来防止幻读？',
      options: ['行锁', '表锁', '间隙锁(Gap Lock)', '不做任何防幻读处理'],
      answer: 2,
      explanation: '快照读(MVCC)天然防幻读；当前读(SELECT FOR UPDATE)通过临键锁(Next-Key Lock = 记录锁+间隙锁)防止幻读。',
      related: ['q33', 'q34', 'q32'] },

    // ========== 软件工程 ==========
    { id: 'q36', category: '软件工程', topic: 'SOLID', difficulty: 2, type: 'choice',
      question: '"一个类应该只有一个引起变化的原因"对应SOLID中的哪个原则？',
      options: ['开闭原则(O)', '里氏替换原则(L)', '单一职责原则(S)', '依赖倒置原则(D)'],
      answer: 2,
      explanation: '单一职责原则(SRP)：一个类只负责一项职责，只有一个引起变化的原因。降低耦合度，提高内聚性。',
      related: ['q37', 'q38'] },

    { id: 'q37', category: '软件工程', topic: '设计模式', difficulty: 2, type: 'choice',
      question: '单例模式中，以下哪种实现方式天然防止反射和序列化破坏？',
      options: ['饿汉式', '双重检查锁(DCL)', '静态内部类', '枚举单例'],
      answer: 3,
      explanation: '枚举单例由JVM保证唯一性，天然防止反射创建新实例和序列化/反序列化破坏，是Effective Java推荐的最优实现。',
      related: ['q36', 'q38'] },

    { id: 'q38', category: '软件工程', topic: 'RESTful', difficulty: 1, type: 'choice',
      question: 'RESTful API中，删除资源应该使用哪个HTTP方法？',
      options: ['GET', 'POST', 'PUT', 'DELETE'],
      answer: 3,
      explanation: 'RESTful规范：GET查询、POST创建、PUT整体更新、DELETE删除、PATCH局部更新。DELETE方法用于删除指定资源。',
      related: ['q36', 'q37'] },

    // ========== 计算机组成 ==========
    { id: 'q39', category: '计算机组成', topic: 'Cache', difficulty: 2, type: 'choice',
      question: 'CPU Cache利用的原理是？',
      options: ['空间局部性', '时间局部性', '空间和时间局部性', '虚拟内存'],
      answer: 2,
      explanation: 'Cache利用两种局部性：时间局部性(刚访问的数据可能再次访问)和空间局部性(被访问数据附近的数据可能被访问)。Cache Line正是为空间局部性设计。',
      related: ['q40', 'q24'] },

    { id: 'q40', category: '计算机组成', topic: '虚拟存储器', difficulty: 3, type: 'choice',
      question: 'TLB(Translation Lookaside Buffer)的作用是？',
      options: ['缓存磁盘数据', '缓存最近使用的页表项，加速地址转换', '缓存CPU指令', '缓存网络数据'],
      answer: 1,
      explanation: 'TLB是页表的高速缓存，缓存最近使用的虚拟地址到物理地址的映射。TLB命中可避免一次内存访问查页表，大幅加速地址转换。',
      related: ['q39', 'q23'] }
];
